name: Basic Vault CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  check-vault:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run duplicate/orphan checks
        run: |
          python scripts/check_note_hygiene.py
